# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
cache: packages

warnings_are_errors: true

r_github_packages:
  - r-lib/covr

after_success:
    - Rscript -e 'covr::codecov()'

